### ISSUE TITLE
Swapping outfits creates an exception when running the AloysAdjustments

### ISSUE THREAD

**Issue by BelowZeroLH** [AkiniKites/AloysAdjustments#32]
Swapping outfits creates an exception when reloading AloysAdjustments even after removing ALL other mods. It occurs in version 1.6 + when I install the pack and reload AloysAdjustments. I tried something simple like swapping "Nora Protector Light" for "Armor - Nora Brave", and then several others. None work unless I go back and use version 1.5.

The following error is placed in the error.log (from 1.8):

`System.NullReferenceException: Object reference not set to an instance of an object.
   at AloysAdjustments.Logic.HzdCoreExtensions.GetTypes[T](HzdCore core)
   at AloysAdjustments.Plugins.Outfits.OutfitsGenerator.GetPlayerModels(HzdCore core)
   at AloysAdjustments.Plugins.Outfits.OutfitsGenerator.GenerateModelList(Func'2 coreGetter)
   at AloysAdjustments.Plugins.Outfits.OutfitCharacterGenerator.<GetVariantMapping>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AloysAdjustments.Plugins.Outfits.OutfitsControl.<LoadPatch>d__60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at AloysAdjustments.MainWindow.<LoadExistingPack>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AloysAdjustments.MainWindow.<btnLoadPatch_Click>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AloysAdjustments.UI.Relay.<To>d__1'2.MoveNext()`

**Comment by AkiniKites** [comment]
Fixed in 1.8.1
